// Auto-generated by main.py — do not edit manually
window.ARCHIVE = [
  {
    "date": "April 27, 2026",
    "iso": "2026-04-27",
    "issue": 1,
    "weekday": "Monday",
    "readMin": 4,
    "tldr": "Jury selection begins today in the Musk vs. Altman OpenAI trial, putting $150 billion in damages and the future of AI governance on the line. Meanwhile, OpenAI quietly rolled out GPT-5.5 to paid ChatGPT users and Google doubled down on Anthropic with a $40 billion investment.",
    "headline": "court drama",
    "categories": [
      {
        "id": "tools",
        "emoji": "\ud83d\udd27",
        "name": "Tools & Products",
        "tagline": "What shipped today",
        "blurb": "New model releases and platform updates reshaping how developers and consumers use AI.",
        "accent": "pink",
        "stories": [
          {
            "title": "GPT-5.5 rolls out to ChatGPT paid users",
            "summary": "OpenAI began a gradual rollout of GPT-5.5 and GPT-5.5 Pro to Plus, Pro, Business, and Enterprise ChatGPT subscribers today. The new Thinking variant is pitched as the most capable reasoning model in ChatGPT, able to handle complex multi-step tasks, while API access will follow later with additional safeguards in place.",
            "source": "help.openai.com",
            "url": "https://help.openai.com/zh-hant-hk/articles/11909943-chatgpt-%E4%B8%AD%E7%9A%84-gpt-53-%E8%88%87-gpt-55",
            "tags": [
              "openai",
              "models",
              "chatgpt"
            ]
          },
          {
            "title": "OpenAI splits ChatGPT Pro into $100 and $200 tiers",
            "summary": "OpenAI restructured its Pro offering into two tiers: $100/month for 5x usage versus Plus, and $200/month for 20x usage, both including access to GPT-5.5 Pro, Codex, and Deep Research. The $100 tier launches with a temporary 10x Codex bonus through May 31 to sweeten the deal.",
            "source": "help.openai.com",
            "url": "https://help.openai.com/fr-fr/articles/9793128-about-chatgpt-pro-tiers",
            "tags": [
              "openai",
              "pricing",
              "chatgpt"
            ]
          },
          {
            "title": "ComfyUI hits $500M valuation after $30M raise",
            "summary": "ComfyUI, the open-source node-based tool that gives creators granular control over AI image, video, and audio generation, closed a $30 million funding round at a $500 million valuation. The raise reflects growing demand from creators who want more hands-on control than turnkey AI apps provide.",
            "source": "techcrunch.com",
            "url": "https://techcrunch.com/category/artificial-intelligence/",
            "tags": [
              "image-gen",
              "creative-tools",
              "funding"
            ]
          },
          {
            "title": "Replicate adds Moonshot Kimi-K2 and Alibaba Happy Horse",
            "summary": "Replicate's official model catalog expanded this week with Moonshot AI's Kimi-K2, a one-trillion-parameter open model built for long-horizon coding and agent swarms with a 262k context window. Alibaba's Happy Horse 1.0 also landed, offering text-to-video and image-to-video generation at 720p and 1080p.",
            "source": "replicate.com",
            "url": "https://replicate.com/collections/official",
            "tags": [
              "models",
              "video-gen",
              "devtools"
            ]
          }
        ]
      },
      {
        "id": "money",
        "emoji": "\ud83d\udcb0",
        "name": "Startups & Money",
        "tagline": "Who got paid",
        "blurb": "The funding rounds, acquisitions, and valuation milestones moving AI capital this week.",
        "accent": "lilac",
        "stories": [
          {
            "title": "DeepMind's David Silver raises $1.1B for data-free AI lab",
            "summary": "Ineffable Intelligence, a British AI lab founded just months ago by AlphaGo creator David Silver, secured $1.1 billion at a $5.1 billion valuation. The lab is pursuing AI systems that learn without human-labeled data, a fundamental departure from how most frontier models are trained today.",
            "source": "techcrunch.com",
            "url": "https://techcrunch.com/category/artificial-intelligence/",
            "tags": [
              "seed",
              "research",
              "uk"
            ]
          },
          {
            "title": "Google commits up to $40B to Anthropic",
            "summary": "Google announced plans to invest up to $40 billion in Anthropic in a combination of cash and compute, cementing its position as the startup's largest backer. The deal follows the limited release of Anthropic's cybersecurity-focused Mythos model and comes as Anthropic's annualized revenue reportedly surged past $30 billion.",
            "source": "techcrunch.com",
            "url": "https://techcrunch.com/category/artificial-intelligence/",
            "tags": [
              "google",
              "anthropic",
              "mega-round"
            ]
          },
          {
            "title": "OpenAI resolves Microsoft conflict over AWS deal",
            "summary": "OpenAI has secured major concessions from Microsoft that clear the path for it to sell products on Amazon Web Services, ending a legal dispute between the two companies. In exchange, Microsoft receives an expanded revenue-share agreement, signaling a careful rebalancing of one of AI's most important partnerships.",
            "source": "techcrunch.com",
            "url": "https://techcrunch.com/category/artificial-intelligence/",
            "tags": [
              "openai",
              "microsoft",
              "aws",
              "deals"
            ]
          },
          {
            "title": "Sierra acquires YC-backed Fragment",
            "summary": "Sierra, the AI customer service agent company co-founded by Bret Taylor, has acquired Fragment, a French YC-backed startup. The acquisition is expected to deepen Sierra's capabilities as demand for enterprise-grade AI agents accelerates across industries.",
            "source": "techcrunch.com",
            "url": "https://techcrunch.com/category/artificial-intelligence/",
            "tags": [
              "acquisition",
              "agents",
              "enterprise"
            ]
          },
          {
            "title": "120,000 authors chase share of Anthropic's $1.5B copyright settlement",
            "summary": "Nearly 120,000 authors and copyright holders have filed to claim a portion of a $1.5 billion class-action settlement with Anthropic over unauthorized use of their books in AI training data. The settlement is among the largest copyright resolutions in the AI industry and could set precedent for future training-data disputes.",
            "source": "economictimes.indiatimes.com",
            "url": "https://economictimes.indiatimes.com/topic/us-judges-ai-policies",
            "tags": [
              "copyright",
              "anthropic",
              "legal"
            ]
          }
        ]
      },
      {
        "id": "world",
        "emoji": "\ud83c\udf10",
        "name": "The Bigger Picture",
        "tagline": "Policy, drama, court",
        "blurb": "Courtrooms, regulators, and geopolitics collide as AI's societal stakes come into sharp relief.",
        "accent": "lime",
        "stories": [
          {
            "title": "Musk vs. Altman trial kicks off with $150B on the line",
            "summary": "Jury selection began Monday in San Francisco for Elon Musk's lawsuit against Sam Altman and OpenAI, with opening arguments set for Tuesday. Musk claims OpenAI betrayed its nonprofit charter when it pivoted toward profit, and he is seeking up to $150 billion in damages for its charitable arm \u2014 a verdict that could reshape AI governance and nonprofit law.",
            "source": "economictimes.indiatimes.com",
            "url": "https://economictimes.indiatimes.com/topic/us-judges-ai-policies",
            "tags": [
              "openai",
              "legal",
              "musk"
            ]
          },
          {
            "title": "600 Google employees demand CEO reject classified Pentagon AI deal",
            "summary": "More than 600 Google staff signed an open letter urging CEO Sundar Pichai to turn down a proposed Defense Department contract that would extend Gemini's capabilities into classified military operations. Google already holds a non-classified AI contract with the DoD, making this a direct escalation of the long-running employee activism over military AI.",
            "source": "economictimes.indiatimes.com",
            "url": "https://economictimes.indiatimes.com/topic/us-judges-ai-policies",
            "tags": [
              "google",
              "military",
              "policy"
            ]
          },
          {
            "title": "US judges scramble to set AI policies for their chambers",
            "summary": "Federal judges across the country are grappling with how AI tools should \u2014 and should not \u2014 be used in court filings and legal research, with policies ranging from outright bans to cautious endorsements. The patchwork approach reflects broader uncertainty about AI reliability after several high-profile incidents of AI-generated errors in legal documents.",
            "source": "economictimes.indiatimes.com",
            "url": "https://economictimes.indiatimes.com/topic/us-judges-ai-policies",
            "tags": [
              "courts",
              "regulation",
              "legal"
            ]
          },
          {
            "title": "BXAI-OS listed in NIST catalog ahead of Colorado AI deadline",
            "summary": "BXAI-OS has been officially cataloged as a NIST Informative Reference, providing organizations a machine-executable framework for AI governance compliance ahead of Colorado's June 30, 2026 SB 24-205 deadline. The listing arrives as California and New York move toward their own AI regulations, tightening a growing patchwork of state-level AI rules.",
            "source": "morningstar.com",
            "url": "https://www.morningstar.com/news/accesswire/1160965msn/ai-governance-architecture-listed-in-nist-catalog-ahead-of-2026-state-ai-deadlines",
            "tags": [
              "regulation",
              "compliance",
              "nist"
            ]
          }
        ]
      }
    ]
  }
];
