// Auto-generated by main.py — do not edit manually
window.ARCHIVE = [
  {
    "date": "May 2, 2026",
    "iso": "2026-05-02",
    "issue": 6,
    "weekday": "Saturday",
    "readMin": 4,
    "tldr": [
      {
        "catId": "tools",
        "text": "NVIDIA dropped a wave of open models on Hugging Face, headlined by Nemotron 3 Nano \u2014 a 30B hybrid model with a 1M-token context window and 4x faster inference than its predecessor."
      },
      {
        "catId": "money",
        "text": "Anthropic is reportedly days away from closing a round that could value it at over $900 billion, while legal AI startup Legora hit a $5.6B valuation and Meta quietly acquired humanoid robotics startup ARI."
      },
      {
        "catId": "world",
        "text": "Elon Musk's week on the stand against OpenAI went badly, the Pentagon cut Anthropic over 'supply chain risk,' and a dark-money influencer campaign pushing pro-US AI narratives was exposed by Wired."
      }
    ],
    "headline": "musk takes the stand",
    "categories": [
      {
        "id": "tools",
        "emoji": "\ud83d\udd27",
        "name": "Tools & Products",
        "tagline": "What shipped today",
        "blurb": "New models, APIs, and developer tools that landed this week.",
        "accent": "pink",
        "stories": [
          {
            "title": "NVIDIA floods Hugging Face with open models",
            "summary": "NVIDIA released a sweeping collection of open weights and datasets on Hugging Face, anchored by Nemotron 3 Nano \u2014 a 30B-total/3B-active hybrid Mamba-2 + Transformer MoE model with a 1M-token context window and reasoning ON/OFF modes. The release also includes Nemotron Nano VL (12B) for vision-language tasks, Cosmos Predict 2.5 for physics-aware video generation, and millions of rows of multilingual and OCR datasets. Everything ships under permissive licenses with training recipes included.",
            "source": "huggingface.co",
            "url": "https://huggingface.co/nvidia",
            "tags": [
              "open-source",
              "models",
              "nvidia",
              "datasets"
            ]
          },
          {
            "title": "FLUX.2 Max raises the bar for image APIs",
            "summary": "Black Forest Labs' FLUX.2 Max is now the top-tier option on Replicate, supporting up to 8 reference images for character consistency, hex color control for brand accuracy, and structured JSON prompting for precise composition. A distilled 4B-parameter FLUX.2 Klein variant delivers sub-second generation for real-time apps. The lineup cements FLUX as the go-to family for production image pipelines.",
            "source": "replicate.com",
            "url": "https://replicate.com/collections/flux",
            "tags": [
              "image-generation",
              "api",
              "diffusion"
            ]
          },
          {
            "title": "Kling Video 3.0 lands on Replicate with native audio",
            "summary": "Kling Video 3.0 Omni arrived on Replicate with unified multimodal video generation, supporting reference images, video editing, native audio, and multi-shot control in a single model. The standard 3.0 tier generates cinematic clips up to 15 seconds with improved consistency. It joins a growing slate of production-ready video models now available via one-line API calls.",
            "source": "replicate.com",
            "url": "https://replicate.com/collections/official",
            "tags": [
              "video-generation",
              "multimodal",
              "api"
            ]
          },
          {
            "title": "Microsoft embeds a legal agent inside Word",
            "summary": "Microsoft is rolling out a new legal AI agent directly inside Word, designed for legal teams to draft, review, and analyze documents without leaving their workflow. The move is part of a broader push to embed autonomous agents into Microsoft 365 applications. It signals that agentic features are shifting from standalone tools into the software people already use daily.",
            "source": "youtube.com",
            "url": "https://www.youtube.com/watch?v=KVQNFxX1zrc",
            "tags": [
              "agents",
              "enterprise",
              "microsoft",
              "legal"
            ]
          }
        ]
      },
      {
        "id": "money",
        "emoji": "\ud83d\udcb0",
        "name": "Startups & Money",
        "tagline": "Who got paid",
        "blurb": "The funding rounds, acquisitions, and valuations moving the market.",
        "accent": "lilac",
        "stories": [
          {
            "title": "Anthropic closing in on a $900B+ valuation round",
            "summary": "Sources tell TechCrunch that Anthropic could raise a new $50B round at a valuation exceeding $900 billion, potentially closing within two weeks. The round would be one of the largest private financings in tech history and comes as the company faces simultaneous pressure from a Pentagon ban and a high-profile copyright lawsuit. If it closes, it repositions Anthropic as the most valuable private AI lab on earth.",
            "source": "techcrunch.com",
            "url": "https://techcrunch.com/2026/05/02/beyond-lovable-and-mistral-21-european-startups-to-watch/",
            "tags": [
              "anthropic",
              "funding",
              "valuation",
              "ai-safety"
            ]
          },
          {
            "title": "Meta acquires humanoid robotics startup ARI",
            "summary": "Meta has bought Assured Robot Intelligence for an undisclosed sum, folding the team and its co-founders into the Superintelligence Labs research division. The deal is part of a broader industry sprint into humanoid robotics, where forecasts range wildly from Goldman Sachs' $38B by 2035 to Morgan Stanley's $5T by 2050. Meta has now made multiple robotics bets in quick succession as it races to compete in physical AI.",
            "source": "techcrunch.com",
            "url": "https://techcrunch.com/2026/05/01/meta-buys-robotic-startup-to-bolster-its-humanoid-ai-ambitions/",
            "tags": [
              "meta",
              "robotics",
              "acquisition",
              "humanoid"
            ]
          },
          {
            "title": "Legal AI startup Legora hits $5.6B valuation",
            "summary": "Legora has reached a $5.6 billion valuation, intensifying its rivalry with Harvey in the fast-growing legal AI sector. The milestone comes as law firms and enterprise legal teams race to adopt AI-powered drafting and research tools. The competition between Legora and Harvey is shaping up to be one of the defining startup battles of 2026.",
            "source": "techcrunch.com",
            "url": "https://techcrunch.com/2026/04/30/legal-ai-startup-legora-hits-5-6-valuation-and-its-battle-with-harvey-just-got-hotter/",
            "tags": [
              "legal-ai",
              "valuation",
              "enterprise"
            ]
          },
          {
            "title": "Anduril raises ~$4B at a $60B valuation",
            "summary": "Defense tech giant Anduril is closing a roughly $4 billion round led by Andreessen Horowitz and Thrive Capital, valuing the company at $60 billion. The raise cements Anduril's position as the dominant private player in AI-powered defense infrastructure. It also reflects how national security spending is increasingly funneling into AI-native startups rather than legacy contractors.",
            "source": "theinformation.com",
            "url": "https://www.theinformation.com/articles",
            "tags": [
              "defense",
              "funding",
              "a16z",
              "anduril"
            ]
          },
          {
            "title": "Y Combinator alum Skio exits for $105M on just $8M raised",
            "summary": "Skio, a subscription commerce startup that went through Y Combinator, sold for $105 million in cash despite having raised only $8 million \u2014 a rare capital-efficient exit in a market obsessed with mega-rounds. The founder confirmed the deal publicly, making it an instant case study in lean startup strategy. It stands out sharply against the billion-dollar raises dominating the AI headlines this week.",
            "source": "techcrunch.com",
            "url": "https://techcrunch.com",
            "tags": [
              "exit",
              "yc",
              "startup",
              "efficient"
            ]
          }
        ]
      },
      {
        "id": "world",
        "emoji": "\ud83c\udf10",
        "name": "The Bigger Picture",
        "tagline": "Policy, drama, court",
        "blurb": "The legal fights, government moves, and geopolitical tensions shaping AI's future.",
        "accent": "lime",
        "stories": [
          {
            "title": "Musk's courtroom week against OpenAI went sideways",
            "summary": "Elon Musk took the stand in his lawsuit against OpenAI and reportedly spent much of the week arguing with lawyers \u2014 including his own \u2014 and shifting his account of events. Commentators at the Vergecast described him as unlikely to sway a jury that may have already needed heavy persuading. If Musk can't make his version of OpenAI's origins stick, the legal pressure shifts back to the company and the fight moves to documentary evidence.",
            "source": "youtube.com",
            "url": "https://www.youtube.com/watch?v=KVQNFxX1zrc",
            "tags": [
              "musk",
              "openai",
              "lawsuit",
              "court"
            ]
          },
          {
            "title": "Pentagon cuts Anthropic, calls it a supply chain risk",
            "summary": "The Defense Department has designated Anthropic a supply chain risk and barred its products from classified use, a notable reversal after the company had previously worked with the Pentagon. Anthropic had refused to loosen red lines on mass domestic surveillance and fully autonomous weapons, and after its products were banned it sued and won a temporary injunction. The DoD meanwhile signed classified AI deals with OpenAI, xAI, and Palantir.",
            "source": "youtube.com",
            "url": "https://www.youtube.com/watch?v=KVQNFxX1zrc",
            "tags": [
              "anthropic",
              "pentagon",
              "policy",
              "national-security"
            ]
          },
          {
            "title": "Dark money campaign pays influencers to push pro-US AI talking points",
            "summary": "Wired reports that Build American AI, a dark money group tied to a super PAC called Leading the Future and backed by tech figures, is paying creators thousands of dollars per video to promote American AI and frame China as a threat. The campaign uses lifestyle influencers to launder policy messaging as organic content. It raises sharp questions about transparency in AI policy debates happening on social media.",
            "source": "youtube.com",
            "url": "https://www.youtube.com/watch?v=KVQNFxX1zrc",
            "tags": [
              "policy",
              "influence",
              "dark-money",
              "geopolitics"
            ]
          },
          {
            "title": "xAI sues Colorado over its AI Act; DOJ joins in",
            "summary": "xAI filed suit in a Colorado federal court arguing the Colorado AI Act violates the equal protection clause of the Fourteenth Amendment, and the DOJ has moved to intervene in support of xAI's position. Colorado has agreed to a temporary stay on enforcement while the case proceeds. The case is shaping up as a key test of whether states can regulate AI discrimination without running afoul of federal constitutional limits.",
            "source": "insideaipolicy.com",
            "url": "https://insideaipolicy.com",
            "tags": [
              "regulation",
              "colorado",
              "xai",
              "doj",
              "court"
            ]
          },
          {
            "title": "South Korea moves to label all AI-generated media",
            "summary": "South Korea is finalizing amendments that would require AI-generated photos and videos to carry clear labels, while extending compliance obligations across the full content distribution chain \u2014 not just AI developers. Authorities would gain faster tools to block manipulated content, with tougher financial penalties for violations. The framework targets fake celebrity endorsements and synthetic personas in advertising, with ripple effects for any global brand using Korean IP.",
            "source": "kentertechhub.com",
            "url": "https://www.kentertechhub.com/south-korea-tightens-ai-media-rules-as-2026-oversight-takes-shape/",
            "tags": [
              "regulation",
              "south-korea",
              "deepfakes",
              "media"
            ]
          }
        ]
      }
    ]
  },
  {
    "date": "April 30, 2026",
    "iso": "2026-04-30",
    "issue": 4,
    "weekday": "Thursday",
    "readMin": 4,
    "tldr": [
      {
        "catId": "tools",
        "text": "Google's AI Max turns one and expands into Shopping campaigns and travel formats, while inclusionAI open-sources a trillion-parameter model claiming open-source SOTA on coding benchmarks."
      },
      {
        "catId": "money",
        "text": "Anthropic is reportedly in talks to raise a staggering $50B round at a $900B valuation, as AI customer-service startups Netomi and Cresta both hit major milestones."
      },
      {
        "catId": "world",
        "text": "The EU AI Act's high-risk deadline stays intact after the Digital Omnibus deal collapsed in Brussels, leaving founders without the delay they were counting on."
      }
    ],
    "headline": "billion-dollar birthdays",
    "categories": [
      {
        "id": "tools",
        "emoji": "\ud83d\udd27",
        "name": "Tools & Products",
        "tagline": "What shipped today",
        "blurb": "New model drops and ad-tech upgrades signal a busy shipping week.",
        "accent": "pink",
        "stories": [
          {
            "title": "Google AI Max turns one, goes shopping",
            "summary": "Google's AI Max for Search celebrates its first birthday by expanding into Shopping campaigns and travel-specific ad formats. A new Gemini-powered tool called AI Brief lets advertisers steer messaging, audience targeting, and search matching in plain language before committing to any changes. Text disclaimers for regulated industries are also rolling out, finally letting compliance-heavy advertisers use Final URL expansion.",
            "source": "blog.google",
            "url": "https://blog.google/products/ads-commerce/ai-max-new-features/",
            "tags": [
              "google",
              "ads",
              "ai-max"
            ]
          },
          {
            "title": "inclusionAI drops a trillion-parameter open-source model",
            "summary": "Ling-2.6-1T is a one-trillion-parameter model that combines MLA and Linear Attention for lower VRAM and faster inference on long contexts. The team claims open-source SOTA on AIME26, SWE-bench Verified, and several agent execution benchmarks. A 'fast thinking' mechanism cuts chain-of-thought verbosity, reducing token costs without sacrificing reasoning quality.",
            "source": "huggingface.co",
            "url": "https://huggingface.co/inclusionAI/Ling-2.6-1T",
            "tags": [
              "open-source",
              "llm",
              "agents"
            ]
          },
          {
            "title": "IBM Granite gets a multilingual embedding upgrade",
            "summary": "IBM's Granite-Embedding-97M-Multilingual-R2 swaps XLM-RoBERTa for ModernBERT and stretches context from 512 to 32,768 tokens. The 97M parameter model supports 200-plus languages with enhanced retrieval training across 52 of them, plus nine programming languages. It ships with ONNX and OpenVINO exports and posts a 14.5-point average gain over its predecessor on multilingual benchmarks.",
            "source": "huggingface.co",
            "url": "https://huggingface.co/ibm-granite/granite-embedding-97m-multilingual-r2",
            "tags": [
              "ibm",
              "embeddings",
              "open-source"
            ]
          },
          {
            "title": "FLUX 2 lands on Replicate with sub-second generation",
            "summary": "Black Forest Labs' FLUX 2 family is now fully available via Replicate's production API, covering Max, Pro, and the four-billion-parameter Klein model that generates images in under a second. The lineup supports up to ten reference images for multi-image blending and structured JSON prompting for precise camera and lighting control. FLUX.1 Fill, Depth, and Canny round out the suite for inpainting and structure-preserving edits.",
            "source": "replicate.com",
            "url": "https://replicate.com/collections/flux",
            "tags": [
              "image-gen",
              "api",
              "flux"
            ]
          }
        ]
      },
      {
        "id": "money",
        "emoji": "\ud83d\udcb0",
        "name": "Startups & Money",
        "tagline": "Who got paid",
        "blurb": "Nine-figure rounds and near-trillion valuations dominated Thursday's funding headlines.",
        "accent": "lilac",
        "stories": [
          {
            "title": "Anthropic eyes $50B raise at a $900B valuation",
            "summary": "Sources say Anthropic is in talks to close a new $50 billion funding round that would push its valuation toward $900 billion, a figure that would make it one of the most valuable private companies ever. The round comes as the company's Claude models gain traction across enterprise and consumer use cases. No lead investor has been named publicly yet.",
            "source": "techcrunch.com",
            "url": "https://techcrunch.com",
            "tags": [
              "anthropic",
              "funding",
              "mega-round"
            ]
          },
          {
            "title": "Netomi raises $110M with Accenture and Adobe leading",
            "summary": "AI customer-service startup Netomi closed a $110 million round led by Accenture Ventures, with Adobe Ventures, Silver Lake Waterman, and WndrCo also participating. DreamWorks co-founder Jeffrey Katzenberg joins the board, and Accenture has signed a global alliance to bring Netomi to its Fortune 100 client base. The raise lands in a crowded field where Sierra is valued at $10 billion and Decagon at $4.5 billion.",
            "source": "venturebeat.com",
            "url": "https://venturebeat.com/technology/netomi-raises-110-million-as-accenture-and-adobe-bet-on-ai-for-customer-service",
            "tags": [
              "customer-service-ai",
              "funding",
              "enterprise"
            ]
          },
          {
            "title": "137 Ventures pulls in $700M for growth-stage bets",
            "summary": "SpaceX backer 137 Ventures announced two new growth-stage funds totaling more than $700 million, focused on defense, AI, and industrial systems. Founded by former Founders Fund investor Justin Fishner-Wolfson, the firm says it has deployed over a billion dollars in the past year alone. The raise signals continued appetite for late-stage private market exposure in hard-tech.",
            "source": "techcrunch.com",
            "url": "https://techcrunch.com/2026/04/30/spacex-backer-137-ventures-raises-700m-for-two-growth-stage-funds/",
            "tags": [
              "vc",
              "defense",
              "growth-stage"
            ]
          },
          {
            "title": "Cresta quietly hits $100M ARR",
            "summary": "a16z and Sequoia-backed Cresta has crossed $100 million in annual recurring revenue, competing in the same AI customer-service arena as Netomi, Sierra, and Decagon. The company was last valued at $1.6 billion in 2022 and raised a $125 million round in late 2024 at an undisclosed valuation. With revenue now at nine figures, a re-pricing is likely overdue.",
            "source": "axios.com",
            "url": "https://www.axios.com/pro/enterprise-software-deals/2026/04/30/a16z-sequoia-ai-startup-cresta-100-million-arr",
            "tags": [
              "cresta",
              "arr",
              "customer-service-ai"
            ]
          },
          {
            "title": "Legora extends Series D to $600M with Nvidia aboard",
            "summary": "Swedish legal-tech unicorn Legora added a $50 million extension to its Series D, bringing the total to $600 million and valuing the company at $5.6 billion. Nvidia's venture arm NVentures and Atlassian joined as new corporate investors alongside Adams Street Partners, Barclays, and Insight Partners. The extension follows a $550 million raise just six weeks earlier in March.",
            "source": "sifted.eu",
            "url": "https://sifted.eu/articles/backed-by-nvidia-legal-tech-unicorn-legora-extends-series-d-to-600m",
            "tags": [
              "legaltech",
              "nvidia",
              "europe"
            ]
          }
        ]
      },
      {
        "id": "world",
        "emoji": "\ud83c\udf10",
        "name": "The Bigger Picture",
        "tagline": "Policy, drama, court",
        "blurb": "The EU's AI Act reprieve vanished overnight, while US preemption battles heat up across every level of government.",
        "accent": "lime",
        "stories": [
          {
            "title": "EU Omnibus collapses, AI Act deadline holds",
            "summary": "Twelve hours of trilogue negotiations in Brussels ended Monday without a deal, meaning the EU AI Act's Annex III high-risk system deadline remains August 2, 2026 \u2014 not pushed to December 2027 as founders had hoped. The next trilogue is scheduled for May 13, but nothing has changed legally in the meantime. Startups banking on the delay now face a hard compliance sprint.",
            "source": "aigovernanceplaybook.com",
            "url": "https://www.aigovernanceplaybook.com/p/ai-deadline-thursday-30april-2026",
            "tags": [
              "eu-ai-act",
              "regulation",
              "compliance"
            ]
          },
          {
            "title": "White House AI framework pushes federal preemption \u2014 courts will decide",
            "summary": "The White House's March 2026 National Policy Framework for AI strongly endorses federal preemption of state AI laws covering development, liability, and AI-enabled activities, while carving out zoning, fraud, and child safety. Legal experts note an executive order cannot actually preempt state law \u2014 only Congress or the courts can \u2014 and no court has struck down any state AI statute yet. The DOJ AI Litigation Task Force has already joined xAI's lawsuit against Colorado's SB 205 as its opening move.",
            "source": "consumerfinancemonitor.com",
            "url": "https://www.consumerfinancemonitor.com/2026/04/30/todays-podcast-episode-the-white-house-ai-framework-ambition-preemption-and-uncertainty-ahead/",
            "tags": [
              "policy",
              "preemption",
              "white-house"
            ]
          },
          {
            "title": "State AI rules are getting teeth \u2014 and deadlines",
            "summary": "New York mandates AI-generated performer disclosure starting June 9, California requires embedded metadata on all AI content by August 2 with $5,000-per-day fines for stripping it, and Tennessee already treats unauthorized AI voice cloning as a criminal misdemeanor under the ELVIS Act. The FTC, meanwhile, has ramped up AI-washing enforcement with a 40% increase in actions in 2025 and penalties up to $51,744 per violation. Legal experts say the only safe strategy is to build compliance around the strictest applicable state standard now.",
            "source": "billo.app",
            "url": "https://billo.app/blog/us-ai-regulations/",
            "tags": [
              "state-law",
              "ftc",
              "compliance"
            ]
          },
          {
            "title": "Elon Musk takes the stand again in OpenAI trial",
            "summary": "Musk appeared for a second day of testimony in his ongoing legal challenge against OpenAI, a case that observers say could reshape governance norms across the AI industry. The trial centers on whether OpenAI violated its founding nonprofit mission by pursuing a for-profit restructuring. No verdict is expected imminently, but each day of testimony generates fresh public attention on AI corporate structure.",
            "source": "youtube.com",
            "url": "https://www.youtube.com/watch?v=zAT7tVBdgMY",
            "tags": [
              "openai",
              "musk",
              "trial"
            ]
          }
        ]
      }
    ]
  },
  {
    "date": "April 29, 2026",
    "iso": "2026-04-29",
    "issue": 4,
    "weekday": "Wednesday",
    "readMin": 5,
    "tldr": [
      {
        "catId": "tools",
        "text": "Gemini rolls out memory and chat-history import to UK users, letting people port their entire AI context from rival apps directly into Google's assistant."
      },
      {
        "catId": "money",
        "text": "Defense AI startup Scout AI landed $100M Series A to train autonomous military models, while clinical imaging company Aidoc closed a $150M Series E backed by Goldman Sachs and NVIDIA."
      },
      {
        "catId": "world",
        "text": "EU negotiators failed to reach a deal on AI Act amendments after 12 hours of talks, putting an August 2026 high-risk compliance deadline in serious jeopardy."
      }
    ],
    "headline": "rules without a referee",
    "categories": [
      {
        "id": "tools",
        "emoji": "\ud83d\udd27",
        "name": "Tools & Products",
        "tagline": "What shipped today",
        "blurb": "From memory-powered assistants to sub-second image generation, the AI product pace is relentless.",
        "accent": "pink",
        "stories": [
          {
            "title": "Gemini remembers you \u2014 and will steal your ChatGPT history",
            "summary": "Google is rolling out a Memories feature to UK Gemini users that lets the assistant learn preferences across conversations over time. More aggressively, it now lets users import their full chat history and saved memories from rival AI apps via ZIP file or a copy-paste prompt flow. The move is a direct shot at user lock-in across the AI assistant market.",
            "source": "blog.google",
            "url": "https://blog.google/company-news/inside-google/around-the-globe/google-europe/united-kingdom/gemini-launches-new-personalisation-features-in-the-uk/",
            "tags": [
              "gemini",
              "personalization",
              "google"
            ]
          },
          {
            "title": "Kiri.ai drops a 1-trillion-parameter open model on Replicate",
            "summary": "Moonshot AI's Kimi model \u2014 1 trillion parameters, 262k context window, with vision and tool use \u2014 is now available via Replicate's API alongside a wave of other frontier models. The Replicate catalog now spans everything from OpenAI's GPT image generation to Anthropic's Claude Opus 4.7 and ByteDance's multimodal video model. The breadth signals that production-ready model access is becoming a commodity.",
            "source": "replicate.com",
            "url": "https://replicate.com/explore",
            "tags": [
              "open-models",
              "api",
              "devtools"
            ]
          },
          {
            "title": "FLUX 2 Max targets product photography and character consistency",
            "summary": "Black Forest Labs' FLUX 2 family now covers the full spectrum from sub-second prototyping with FLUX 2 Klein to premium fidelity with FLUX 2 Max, which supports up to 8 reference images for character and product consistency. Structured JSON prompting and precise hex color control make it a serious contender for commercial creative workflows. The family is available production-ready via Replicate.",
            "source": "replicate.com",
            "url": "https://replicate.com/collections/flux",
            "tags": [
              "image-gen",
              "creative-tools",
              "api"
            ]
          },
          {
            "title": "Google Translate turns 20 with Gemini-powered idiom smarts",
            "summary": "Google marked the 20th anniversary of Translate by integrating Gemini models into its Live interpretation feature, which now handles slang, idioms, and tonal nuance rather than just literal translation. Earbuds can now act as real-time interpreters that preserve a speaker's rhythm and register. The upgrade reflects how Gemini is quietly becoming the engine behind Google's entire product surface.",
            "source": "blog.google",
            "url": "https://blog.google/intl/zh-tw/products/explore-get-answers/google-translate-20/",
            "tags": [
              "google-translate",
              "gemini",
              "language"
            ]
          },
          {
            "title": "FIDO Alliance sets safety rules for AI agents buying things online",
            "summary": "The FIDO Alliance announced new authentication standards specifically designed for AI agents that shop, log in, and transact on users' behalf. The initiative addresses a fast-growing identity problem: as agents proliferate, most organizations have no controls over which agents access which data or accounts. The standards aim to prevent agents from going rogue with payment credentials before the problem becomes widespread.",
            "source": "aiagentstore.ai",
            "url": "https://aiagentstore.ai/ai-agent-news/2026-april",
            "tags": [
              "ai-agents",
              "security",
              "standards"
            ]
          }
        ]
      },
      {
        "id": "money",
        "emoji": "\ud83d\udcb0",
        "name": "Startups & Money",
        "tagline": "Who got paid",
        "blurb": "Defense AI, medical imaging, and government tech all drew serious checks this week.",
        "accent": "lilac",
        "stories": [
          {
            "title": "Scout AI raises $100M to train models for battlefield ATVs",
            "summary": "Scout AI, a self-described frontier lab for defense founded in 2024, closed a $100M Series A led by Align Ventures and Draper Associates. The startup builds autonomous military all-terrain vehicles and trains the AI models that operate them. It previously raised a $15M seed in January 2025, making this a rapid scale-up in a sector attracting serious venture capital.",
            "source": "techcrunch.com",
            "url": "https://techcrunch.com/2026/04/29/coby-adcocks-scout-ai-raises-100-million-to-train-models-for-war-we-visited-its-bootcamp/",
            "tags": [
              "defense",
              "robotics",
              "series-a"
            ]
          },
          {
            "title": "Aidoc pulls in $150M Series E for clinical AI imaging",
            "summary": "Clinical AI provider Aidoc secured $150M in a Series E led by Goldman Sachs Alternatives, with General Catalyst, SoftBank, and NVIDIA's NVentures also participating. The company, which applies AI to medical imaging workflows, has now raised $520M in total. The round comes weeks after rival RadAI closed a $60M Series C at a $525M valuation, signaling fierce competition in radiology AI.",
            "source": "axios.com",
            "url": "https://www.axios.com/2026/04/29/exclusive-clinical-ai-provider-aidoc-raises-150m-series-e",
            "tags": [
              "healthtech",
              "series-e",
              "medical-ai"
            ]
          },
          {
            "title": "BMW i Ventures launches $300M fund with AI and robotics thesis",
            "summary": "BMW's independent venture arm announced a $300M third fund focused on agentic AI, physical AI, robotics, and industrial software for the automotive sector. The new fund brings BMW i Ventures to $1.1B in total capital under management and will invest from early stage through Series B in North America and Europe. No investments from the new fund have been announced yet.",
            "source": "techcrunch.com",
            "url": "https://techcrunch.com/2026/04/29/bmw-i-ventures-has-a-new-300m-fund-and-ai-is-riding-shotgun/",
            "tags": [
              "corporate-vc",
              "robotics",
              "automotive"
            ]
          },
          {
            "title": "Pursuit lands $22M seed to help companies win government contracts",
            "summary": "Pursuit, a platform that helps businesses find and win government contracts, announced a $22M seed round led by OpenGov co-founder Mike Rosengarten, with backing from Bill Gurley, Jack Altman, and Sam Hinkie. The company launched in 2023 out of a simple observation: selling to government is surprisingly hard for most companies. Total funding now stands at $25.5M.",
            "source": "techcrunch.com",
            "url": "https://techcrunch.com/2026/04/29/bill-gurley-jack-altman-back-startup-pursuit-which-helps-companies-sell-to-government/",
            "tags": [
              "govtech",
              "seed",
              "b2b"
            ]
          },
          {
            "title": "Shapes raises $8M for AI characters in your group chats",
            "summary": "Shapes, an app that embeds AI characters directly into human group conversations, emerged from stealth with $8M in seed funding led by Lightspeed. Think Discord, but where AI personas are full participants in the chat alongside real users. The company plans to use the capital to accelerate user acquisition in what is shaping up to be a crowded social AI space.",
            "source": "techcrunch.com",
            "url": "https://techcrunch.com/2026/04/29/meet-shapes-the-app-bringing-humans-and-ai-into-the-same-group-chats/",
            "tags": [
              "social-ai",
              "seed",
              "consumer"
            ]
          }
        ]
      },
      {
        "id": "world",
        "emoji": "\ud83c\udf10",
        "name": "The Bigger Picture",
        "tagline": "Policy, drama, court",
        "blurb": "Courts, classified contracts, and collapsing EU talks \u2014 AI governance is in full crisis mode.",
        "accent": "lime",
        "stories": [
          {
            "title": "EU AI Act talks collapse after marathon session",
            "summary": "After 12 hours of negotiations, EU member states and European Parliament lawmakers failed to agree on amendments to the AI Act that would have delayed high-risk compliance deadlines from August 2026 to 2027 or later. The core sticking point is whether AI embedded in already-regulated products like medical devices and toys should be exempt from additional AI Act requirements. If talks stall through May and June, companies that built their timelines around the extension could face immediate compliance obligations they are not ready for.",
            "source": "thenextweb.com",
            "url": "https://thenextweb.com/news/eu-ai-act-omnibus-deal-fails-april-2026-talks",
            "tags": [
              "eu-ai-act",
              "regulation",
              "policy"
            ]
          },
          {
            "title": "Google signed a classified AI deal with the Pentagon \u2014 quietly",
            "summary": "Google reportedly agreed to let the US Department of Defense use its AI models for any lawful government purpose under a classified contract, placing it alongside OpenAI and xAI in the set of companies with secret military AI agreements. The deal reportedly bars the company from blocking lawful government uses and requires it to help adjust safety filters when asked. The contract was finalized less than a day after Google employees publicly asked Sundar Pichai to block Pentagon access.",
            "source": "youtube.com",
            "url": "https://www.youtube.com/watch?v=Ub6yRNolFgg",
            "tags": [
              "google",
              "pentagon",
              "defense"
            ]
          },
          {
            "title": "Musk takes the stand in his OpenAI trial",
            "summary": "Elon Musk began testifying in his lawsuit against OpenAI, Sam Altman, and Greg Brockman in a California federal courtroom. Musk is alleging fraud, breach of charitable trust, and unjust enrichment, and is seeking to unwind OpenAI's for-profit restructuring and strip Altman and Brockman of authority. The trial is expected to call major industry witnesses including Microsoft CEO Satya Nadella and former OpenAI CTO Mira Murati.",
            "source": "youtube.com",
            "url": "https://www.youtube.com/watch?v=Ub6yRNolFgg",
            "tags": [
              "openai",
              "musk",
              "litigation"
            ]
          },
          {
            "title": "AI regulation is fracturing into sovereign bubbles",
            "summary": "A new analysis argues that the long-anticipated convergence of global AI rules is not happening \u2014 instead, 2026 is seeing a mosaic of incompatible national regimes. Australia is advancing workplace AI law, Pakistan is restricting government hiring AI, US states are passing a flurry of bills while the White House pushes federal preemption, and the EU can't even agree with itself. For multinationals, the compliance burden is becoming a competitive disadvantage, and shadow AI use is growing as strict internal policies push employees toward personal accounts.",
            "source": "questa-ai.com",
            "url": "https://www.questa-ai.com/privacy-cafe/ai-regulation-in-2026-is-breaking-apart-globally",
            "tags": [
              "regulation",
              "global-policy",
              "compliance"
            ]
          },
          {
            "title": "The US should build AI standards, not bully AI companies",
            "summary": "A sharp analysis argues that the Trump administration's confrontation with Anthropic \u2014 threatening to blacklist the company for refusing to remove safety guardrails from Pentagon access \u2014 is the wrong play, and risks damaging US credibility in international AI governance. The piece draws a historical parallel to how the US shaped the internet by leading protocol standards through DARPA and NIST, and argues that CAISI's new AI Agent Standards Initiative is the right model to follow. Countries considering adopting US-led AI infrastructure are watching the Anthropic episode carefully.",
            "source": "techpolicy.press",
            "url": "https://www.techpolicy.press/the-us-is-fighting-for-control-of-ai-it-would-be-better-off-building-standards/",
            "tags": [
              "us-policy",
              "standards",
              "anthropic"
            ]
          }
        ]
      }
    ]
  },
  {
    "date": "April 28, 2026",
    "iso": "2026-04-28",
    "issue": 2,
    "weekday": "Tuesday",
    "readMin": 5,
    "tldr": [
      {
        "catId": "tools",
        "text": "GitHub Copilot expanded its agent ecosystem with Claude and Codex integrations, marking a shift toward multi-model developer tooling."
      },
      {
        "catId": "money",
        "text": "ComfyUI hit a $500M valuation after raising $30M, making it one of the most valuable open-source AI tool companies."
      },
      {
        "catId": "world",
        "text": "120,000 authors filed for a share of Anthropic's $1.5B copyright settlement, setting a precedent for AI training data compensation."
      }
    ],
    "headline": "musk vs altman",
    "categories": [
      {
        "id": "tools",
        "emoji": "\ud83d\udd27",
        "name": "Tools & Products",
        "tagline": "What shipped today",
        "blurb": "New model releases, developer APIs, and platform updates landed across the AI ecosystem.",
        "accent": "pink",
        "stories": [
          {
            "title": "GitHub Copilot adds Claude and Codex to Agent HQ",
            "summary": "GitHub's Agent HQ now lets developers pick between Anthropic's Claude and OpenAI's Codex directly inside GitHub and VS Code. The feature is in public preview for Copilot Pro+ and Enterprise subscribers, expanding the platform's multi-agent orchestration ambitions first unveiled at Universe 2025.",
            "source": "github.blog",
            "url": "https://github.blog/news-insights/company-news/",
            "tags": [
              "devtools",
              "agents",
              "copilot"
            ]
          },
          {
            "title": "GitHub Copilot SDK opens to all developers",
            "summary": "A new GitHub Copilot SDK is now in technical preview, letting any application embed a programmable agent layer that can plan tasks, invoke tools, edit files, and run commands. GitHub is positioning this as a way to bake AI-native workflows into third-party apps, not just its own surfaces.",
            "source": "github.blog",
            "url": "https://github.blog/news-insights/company-news/",
            "tags": [
              "devtools",
              "sdk",
              "agents"
            ]
          },
          {
            "title": "OpenAI restructures ChatGPT Pro into two tiers",
            "summary": "OpenAI has split its $200 ChatGPT Pro plan, adding a new $100 mid-tier that offers 5x usage limits over Plus and 10x Codex access through May 31. The restructure reflects growing demand for Codex and Deep Research among professional users who don't need the full unlimited-tier firepower.",
            "source": "help.openai.com",
            "url": "https://help.openai.com/id-id/articles/9793128-about-chatgpt-pro-plans",
            "tags": [
              "pricing",
              "openai",
              "chatgpt"
            ]
          },
          {
            "title": "Google donates Agent Payments Protocol to FIDO Alliance",
            "summary": "Google open-sourced version 0.2 of its Agent Payments Protocol (AP2) on GitHub and handed stewardship to the FIDO Alliance. The update introduces 'Human Not Present' payment flows, allowing AI agents to autonomously complete pre-authorized purchases \u2014 like snagging concert tickets the instant they go on sale.",
            "source": "blog.google",
            "url": "https://blog.google/products-and-platforms/platforms/google-pay/agent-payments-protocol-fido-alliance/",
            "tags": [
              "agents",
              "payments",
              "standards"
            ]
          },
          {
            "title": "FLUX.2 family brings sub-second image gen to production",
            "summary": "Black Forest Labs' FLUX.2 lineup on Replicate now spans three tiers: Max for ultra-high-fidelity product photography, Pro for high-volume editing with structured JSON prompting, and Klein 4B \u2014 a 4-billion-parameter distilled model capable of sub-second generation for real-time apps. All tiers support multi-reference image blending.",
            "source": "replicate.com",
            "url": "https://replicate.com/collections/flux",
            "tags": [
              "image-gen",
              "api",
              "black-forest-labs"
            ]
          }
        ]
      },
      {
        "id": "money",
        "emoji": "\ud83d\udcb0",
        "name": "Startups & Money",
        "tagline": "Who got paid",
        "blurb": "Big checks flew across AI infrastructure, insurtech, defense, and fintech this week.",
        "accent": "lilac",
        "stories": [
          {
            "title": "DeepMind co-founder raises $1.1B for Ineffable Intelligence",
            "summary": "David Silver, the DeepMind researcher behind AlphaGo, has secured $1.1 billion for his new British AI lab Ineffable Intelligence at a $5.1 billion valuation. The startup is pursuing AI systems that learn without human-labeled data, betting on reinforcement learning as the path to more autonomous AI.",
            "source": "youtube.com",
            "url": "https://www.youtube.com/watch?v=g6fPa1pfpF0",
            "tags": [
              "funding",
              "research",
              "reinforcement-learning"
            ]
          },
          {
            "title": "Tencent and Alibaba circle DeepSeek at $20B+ valuation",
            "summary": "Chinese tech giants Tencent and Alibaba are in advanced talks to invest in DeepSeek, the AI lab owned by hedge fund High-Flyer Capital Management, at a valuation exceeding $20 billion. It would be DeepSeek's first external fundraise, underscoring how seriously Chinese incumbents are taking the upstart's rapid rise.",
            "source": "theinformation.com",
            "url": "https://www.theinformation.com/topics/tencent",
            "tags": [
              "funding",
              "china",
              "deepseek"
            ]
          },
          {
            "title": "Space defense startup True Anomaly lands $650M Series D",
            "summary": "True Anomaly, which builds autonomous spacecraft and software for U.S. national security missions, closed a $650 million Series D that lifts its total funding to $1 billion. The round signals sustained investor appetite for AI-driven defense technology as geopolitical tensions around space assets intensify.",
            "source": "axios.com",
            "url": "https://www.axios.com/pro/all-deals/2026/04/28/space-defense-true-anomaly-650-million",
            "tags": [
              "defense",
              "space",
              "series-d"
            ]
          },
          {
            "title": "Counterpart raises $96M to insure AI-related damage",
            "summary": "Insurtech startup Counterpart closed a $96 million round, bringing total capital to $106 million, to expand its AI-powered liability insurance products. The raise comes as enterprises face mounting legal exposure from AI errors, bias claims, and regulatory penalties.",
            "source": "axios.com",
            "url": "https://www.axios.com/pro/fintech-deals/2026/04/28/counterpart-ai-insurance-96-million",
            "tags": [
              "insurtech",
              "funding",
              "risk"
            ]
          },
          {
            "title": "Windmill pulls $12M to reinvent AI-era performance reviews",
            "summary": "HR tech startup Windmill raised $12 million across pre-seed and seed rounds to build fairer, more frequent performance evaluations using AI. The founders argue that as AI-driven workplace anxiety grows, companies need objective and auditable feedback systems that reduce managerial bias.",
            "source": "axios.com",
            "url": "https://www.axios.com/pro/enterprise-software-deals/2026/04/28/hr-tech-windmill-performance-ai",
            "tags": [
              "hr-tech",
              "seed",
              "workplace-ai"
            ]
          }
        ]
      },
      {
        "id": "world",
        "emoji": "\ud83c\udf10",
        "name": "The Bigger Picture",
        "tagline": "Policy, drama, court",
        "blurb": "Courts, regulators, and geopolitical rivalries are reshaping the rules of the AI game.",
        "accent": "lime",
        "stories": [
          {
            "title": "Musk vs. Altman trial kicks off in California",
            "summary": "Jury selection began Monday in San Francisco for Elon Musk's lawsuit against Sam Altman and OpenAI, with opening arguments set for Tuesday. Musk is seeking up to $150 billion in damages, alleging OpenAI betrayed its nonprofit charter when it pivoted toward a for-profit structure \u2014 a case that could redefine how AI companies are legally obligated to honor their founding missions.",
            "source": "economictimes.indiatimes.com",
            "url": "https://economictimes.indiatimes.com/topic/us-judges-ai-policies",
            "tags": [
              "lawsuit",
              "openai",
              "musk"
            ]
          },
          {
            "title": "DOJ backs xAI lawsuit to kill Colorado's AI Act",
            "summary": "The Department of Justice intervened on April 24 in xAI's lawsuit challenging Colorado's sweeping AI Act, marking the first time the federal government has moved to invalidate a state AI law under Trump's Executive Order 14365. The DOJ argued the law violates the Equal Protection Clause by compelling AI companies to factor demographic characteristics into model design, framing state-level AI regulation as a barrier to national competitiveness.",
            "source": "governmentcontractorcomplianceupdate.com",
            "url": "https://www.governmentcontractorcomplianceupdate.com/2026/04/28/federal-government-intervenes-in-case-seeking-to-invalidate-colorado-ai-law/",
            "tags": [
              "regulation",
              "colorado",
              "doj"
            ]
          },
          {
            "title": "China blocks Meta's $2B acquisition of Manus",
            "summary": "Beijing formally blocked Meta's $2 billion bid to acquire Manus, an AI agent startup, following a months-long regulatory probe. The decision underscores how cross-border AI acquisitions are increasingly caught in geopolitical crossfire, with data sovereignty and AI agent capabilities now treated as strategic national interests.",
            "source": "cnbc.com",
            "url": "https://www.cnbc.com/2026/04/27/meta-manus-china-blocks-acquisition-ai-startup.html",
            "tags": [
              "geopolitics",
              "meta",
              "regulation"
            ]
          },
          {
            "title": "OpenAI ends Microsoft exclusivity, expands to AWS",
            "summary": "OpenAI has resolved its long-running legal and commercial tensions with Microsoft, clearing the way to offer its models on Amazon Web Services and potentially other cloud providers. The deal marks a significant shift from the exclusive Azure partnership that defined OpenAI's commercial infrastructure for years.",
            "source": "reuters.com",
            "url": "https://www.reuters.com/legal/litigation/microsoft-end-exclusive-license-openais-technology-2026-04-27/",
            "tags": [
              "openai",
              "microsoft",
              "cloud"
            ]
          },
          {
            "title": "AI's regulatory honeymoon is officially over in 2026",
            "summary": "A wave of major AI regulations is hitting simultaneously: the EU AI Act's high-risk provisions take full effect in August with penalties up to \u20ac35 million, Colorado's AI Act is due June 30, California's AI Transparency Act kicks in by August, and a 42-state attorney general coalition is ramping up coordinated enforcement. Companies that treated compliance as optional are now facing a hard reckoning.",
            "source": "kavout.com",
            "url": "https://www.kavout.com/market-lens/is-the-ai-regulatory-honeymoon-truly-over",
            "tags": [
              "regulation",
              "compliance",
              "eu-ai-act"
            ]
          }
        ]
      }
    ]
  },
  {
    "date": "April 27, 2026",
    "iso": "2026-04-27",
    "issue": 1,
    "weekday": "Monday",
    "readMin": 4,
    "tldr": "Jury selection begins today in the Musk vs. Altman OpenAI trial, putting $150 billion in damages and the future of AI governance on the line. Meanwhile, OpenAI quietly rolled out GPT-5.5 to paid ChatGPT users and Google doubled down on Anthropic with a $40 billion investment.",
    "headline": "court drama",
    "categories": [
      {
        "id": "tools",
        "emoji": "\ud83d\udd27",
        "name": "Tools & Products",
        "tagline": "What shipped today",
        "blurb": "New model releases and platform updates reshaping how developers and consumers use AI.",
        "accent": "pink",
        "stories": [
          {
            "title": "GPT-5.5 rolls out to ChatGPT paid users",
            "summary": "OpenAI began a gradual rollout of GPT-5.5 and GPT-5.5 Pro to Plus, Pro, Business, and Enterprise ChatGPT subscribers today. The new Thinking variant is pitched as the most capable reasoning model in ChatGPT, able to handle complex multi-step tasks, while API access will follow later with additional safeguards in place.",
            "source": "help.openai.com",
            "url": "https://help.openai.com/zh-hant-hk/articles/11909943-chatgpt-%E4%B8%AD%E7%9A%84-gpt-53-%E8%88%87-gpt-55",
            "tags": [
              "openai",
              "models",
              "chatgpt"
            ]
          },
          {
            "title": "OpenAI splits ChatGPT Pro into $100 and $200 tiers",
            "summary": "OpenAI restructured its Pro offering into two tiers: $100/month for 5x usage versus Plus, and $200/month for 20x usage, both including access to GPT-5.5 Pro, Codex, and Deep Research. The $100 tier launches with a temporary 10x Codex bonus through May 31 to sweeten the deal.",
            "source": "help.openai.com",
            "url": "https://help.openai.com/fr-fr/articles/9793128-about-chatgpt-pro-tiers",
            "tags": [
              "openai",
              "pricing",
              "chatgpt"
            ]
          },
          {
            "title": "ComfyUI hits $500M valuation after $30M raise",
            "summary": "ComfyUI, the open-source node-based tool that gives creators granular control over AI image, video, and audio generation, closed a $30 million funding round at a $500 million valuation. The raise reflects growing demand from creators who want more hands-on control than turnkey AI apps provide.",
            "source": "techcrunch.com",
            "url": "https://techcrunch.com/category/artificial-intelligence/",
            "tags": [
              "image-gen",
              "creative-tools",
              "funding"
            ]
          },
          {
            "title": "Replicate adds Moonshot Kimi-K2 and Alibaba Happy Horse",
            "summary": "Replicate's official model catalog expanded this week with Moonshot AI's Kimi-K2, a one-trillion-parameter open model built for long-horizon coding and agent swarms with a 262k context window. Alibaba's Happy Horse 1.0 also landed, offering text-to-video and image-to-video generation at 720p and 1080p.",
            "source": "replicate.com",
            "url": "https://replicate.com/collections/official",
            "tags": [
              "models",
              "video-gen",
              "devtools"
            ]
          }
        ]
      },
      {
        "id": "money",
        "emoji": "\ud83d\udcb0",
        "name": "Startups & Money",
        "tagline": "Who got paid",
        "blurb": "The funding rounds, acquisitions, and valuation milestones moving AI capital this week.",
        "accent": "lilac",
        "stories": [
          {
            "title": "DeepMind's David Silver raises $1.1B for data-free AI lab",
            "summary": "Ineffable Intelligence, a British AI lab founded just months ago by AlphaGo creator David Silver, secured $1.1 billion at a $5.1 billion valuation. The lab is pursuing AI systems that learn without human-labeled data, a fundamental departure from how most frontier models are trained today.",
            "source": "techcrunch.com",
            "url": "https://techcrunch.com/category/artificial-intelligence/",
            "tags": [
              "seed",
              "research",
              "uk"
            ]
          },
          {
            "title": "Google commits up to $40B to Anthropic",
            "summary": "Google announced plans to invest up to $40 billion in Anthropic in a combination of cash and compute, cementing its position as the startup's largest backer. The deal follows the limited release of Anthropic's cybersecurity-focused Mythos model and comes as Anthropic's annualized revenue reportedly surged past $30 billion.",
            "source": "techcrunch.com",
            "url": "https://techcrunch.com/category/artificial-intelligence/",
            "tags": [
              "google",
              "anthropic",
              "mega-round"
            ]
          },
          {
            "title": "OpenAI resolves Microsoft conflict over AWS deal",
            "summary": "OpenAI has secured major concessions from Microsoft that clear the path for it to sell products on Amazon Web Services, ending a legal dispute between the two companies. In exchange, Microsoft receives an expanded revenue-share agreement, signaling a careful rebalancing of one of AI's most important partnerships.",
            "source": "techcrunch.com",
            "url": "https://techcrunch.com/category/artificial-intelligence/",
            "tags": [
              "openai",
              "microsoft",
              "aws",
              "deals"
            ]
          },
          {
            "title": "Sierra acquires YC-backed Fragment",
            "summary": "Sierra, the AI customer service agent company co-founded by Bret Taylor, has acquired Fragment, a French YC-backed startup. The acquisition is expected to deepen Sierra's capabilities as demand for enterprise-grade AI agents accelerates across industries.",
            "source": "techcrunch.com",
            "url": "https://techcrunch.com/category/artificial-intelligence/",
            "tags": [
              "acquisition",
              "agents",
              "enterprise"
            ]
          },
          {
            "title": "120,000 authors chase share of Anthropic's $1.5B copyright settlement",
            "summary": "Nearly 120,000 authors and copyright holders have filed to claim a portion of a $1.5 billion class-action settlement with Anthropic over unauthorized use of their books in AI training data. The settlement is among the largest copyright resolutions in the AI industry and could set precedent for future training-data disputes.",
            "source": "economictimes.indiatimes.com",
            "url": "https://economictimes.indiatimes.com/topic/us-judges-ai-policies",
            "tags": [
              "copyright",
              "anthropic",
              "legal"
            ]
          }
        ]
      },
      {
        "id": "world",
        "emoji": "\ud83c\udf10",
        "name": "The Bigger Picture",
        "tagline": "Policy, drama, court",
        "blurb": "Courtrooms, regulators, and geopolitics collide as AI's societal stakes come into sharp relief.",
        "accent": "lime",
        "stories": [
          {
            "title": "Musk vs. Altman trial kicks off with $150B on the line",
            "summary": "Jury selection began Monday in San Francisco for Elon Musk's lawsuit against Sam Altman and OpenAI, with opening arguments set for Tuesday. Musk claims OpenAI betrayed its nonprofit charter when it pivoted toward profit, and he is seeking up to $150 billion in damages for its charitable arm \u2014 a verdict that could reshape AI governance and nonprofit law.",
            "source": "economictimes.indiatimes.com",
            "url": "https://economictimes.indiatimes.com/topic/us-judges-ai-policies",
            "tags": [
              "openai",
              "legal",
              "musk"
            ]
          },
          {
            "title": "600 Google employees demand CEO reject classified Pentagon AI deal",
            "summary": "More than 600 Google staff signed an open letter urging CEO Sundar Pichai to turn down a proposed Defense Department contract that would extend Gemini's capabilities into classified military operations. Google already holds a non-classified AI contract with the DoD, making this a direct escalation of the long-running employee activism over military AI.",
            "source": "economictimes.indiatimes.com",
            "url": "https://economictimes.indiatimes.com/topic/us-judges-ai-policies",
            "tags": [
              "google",
              "military",
              "policy"
            ]
          },
          {
            "title": "US judges scramble to set AI policies for their chambers",
            "summary": "Federal judges across the country are grappling with how AI tools should \u2014 and should not \u2014 be used in court filings and legal research, with policies ranging from outright bans to cautious endorsements. The patchwork approach reflects broader uncertainty about AI reliability after several high-profile incidents of AI-generated errors in legal documents.",
            "source": "economictimes.indiatimes.com",
            "url": "https://economictimes.indiatimes.com/topic/us-judges-ai-policies",
            "tags": [
              "courts",
              "regulation",
              "legal"
            ]
          },
          {
            "title": "BXAI-OS listed in NIST catalog ahead of Colorado AI deadline",
            "summary": "BXAI-OS has been officially cataloged as a NIST Informative Reference, providing organizations a machine-executable framework for AI governance compliance ahead of Colorado's June 30, 2026 SB 24-205 deadline. The listing arrives as California and New York move toward their own AI regulations, tightening a growing patchwork of state-level AI rules.",
            "source": "morningstar.com",
            "url": "https://www.morningstar.com/news/accesswire/1160965msn/ai-governance-architecture-listed-in-nist-catalog-ahead-of-2026-state-ai-deadlines",
            "tags": [
              "regulation",
              "compliance",
              "nist"
            ]
          }
        ]
      }
    ]
  }
];
